name: keyboard_actions_example
description: Exemplo de implementação do KeyboardController para resolver o problema do botão "Done" no teclado iOS.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  keyboard_actions: ^4.2.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
